name: 🎅 [Dataverse Training Labs] Bug, question or feature ask report
description: File a Bug, question or feature ask report for the Dataverse Training Labs
title: "[Dataverse Training Labs] TOPIC TITLE"
labels: ["dataverse labs"]
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Which step is this Bug, question or feature ask related to? (if relevant)
    placeholder: "1.1.1."
  validations:
    required: false
