name: 🤸‍♀️ [Solution Deployer] Bug, question or feature ask report
description: File a Bug, question or feature ask report for the Solution Deployer
title: "[Solution Deployer] TOPIC TITLE"
labels: ["solution deployer"]
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: What solution version are you using? (if relevant)
    placeholder: "2024.03.15.0"
- type: dropdown
  id: component
  attributes:
    label: What solution is related to this Bug, question, or feature ask? (if relevant)
    options:
      - Solution Deployer
      - Solution Deployer Dataflow Addon
  validations:
    required: false
