name: 🎁 [DLP Policy Toolbox] Bug, question or feature ask report
description: File a Bug, question or feature ask report for the DLP Policy Toolbox
title: "[DLP Policy Toolbox] TOPIC TITLE"
labels: ["dlp policy toolbox"]
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: What solution version are you using? (if relevant)
    placeholder: "2023.10.20.1"
  validations:
    required: false
