name: 🐨 [Endpoint Collector] Bug, question or feature ask report
description: File a Bug, question or feature ask report for the Endpoint Collector solution
title: "[Endpoint Collector] TOPIC TITLE"
labels: ["Endpoint Collector"]
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: What solution version are you using? (if relevant)
    placeholder: "2025.03.18.4"