name: 👌 [PPAC Reports Extractor] Bug, question or feature ask report
description: File a Bug, question or feature ask report for the PPAC Reports Extractor
title: "[PPAC Reports Extractor] TOPIC TITLE"
labels: ["ppac reports extractor"]
body:
- type: textarea
  attributes:
    label: Describe your bug, question or feature ask.
    description: A concise description of what issue you are experiencing, what question you have or what feature you would like to see.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: What solution version are you using? (if relevant)
    placeholder: "2023.11.03.2"
  validations:
    required: false
- type: dropdown
  id: component
  attributes:
    label: What component is related to this Bug, question, or feature ask? (if relevant)
    options:
      - Daily Data Load Requestor flow
      - Data Load Executor flow
      - Manual Data Load Requestor flow
      - PpacReports - Manual Request App
      - Other
  validations:
    required: false